name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Images
        run: |
          cd client
          docker build -t client:latest .
          cd ../server
          docker build -t server:latest .

      - name: Run Server and Client in Docker
        run: |
          docker run -d --name server server:latest
          docker run --network=host client:latest

      - name: Run Tests
        run: |
          ./test_commands.sh
