name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Images
        run: |
          cd client
          docker build -t client:latest .
          cd ../server
          docker build -t server:latest .

      - name: Run Server and Client in Docker
        run: |
          docker run -d --network=host --name server server:latest
          
          echo "Waiting for server to start..."
          for i in {1..10}; do
            if nc -z localhost 1234; then
              echo "Server is up."
              break
            else
              echo "Waiting... $i"
              sleep 5
            fi
          done
               
          docker run --network=host client:latest

      - name: Run Tests
        run: |
          ./test_commands.sh
